### PR TITLE
Removed duplicate properties in the pom and maven-shade-plugin upgrade

### PR DESCRIPTION
**Pull request by Jupiops**
Removed duplicate properties and java version declaration in the pom files and updated maven-shade-plugin from SNAPSHOT version 3.3.0 to major version 3.4.0 :arrow_up::art:

### CODE REVIEW

**Comment by Jupiops** [comment]
I had issues getting the SNAPSHOT version of the maven-shade-plugin from maven central

**Comment by cerus** [comment]
Looks good to me, does the project compile?

**Review by cerus — APPROVED** [review]

**Comment by cerus** [comment]
@Jupiops Is your pr ready to be merged?

**Review by cerus — APPROVED** [review]

**Comment by cerus** [comment]
Thanks for the contribution!

**Pull request merged**
